// @ts-nocheck
import { HelpCategories } from "@/lib/types";

export const helpCategories: HelpCategories = {
  "getting-started": {
    id: "3943118",
    iconName: "FlagTriangle",
    title: "Getting Started",
    description: "Alle-AI overview, examples and tips",
    sections: [
      {
        articles: [
          {
            id: "What-is-alle-ai",
            title: "What is Alle-AI",
          },
        ],
      },
    ],
    uniqueRoute: true,
    href: "/hub/getting-started",
  },
  "3943089-account-login-and-billing": {
    id: "3943089",
    iconName: "Settings",
    title: "Account, login and billing",
    description: "Refund requests, billing and login issues",
    sections: [
      {
        title: "Login & Authentication",
        articles: [
          {
            id: "reset-password",
            title: "Why can't I reset my password?",
            description: "Troubleshooting steps for password reset issues",
            readingTime: "3 min read",
            keywords: [
              "password reset issues",
              "cannot reset password",
              "email troubleshooting",
              "password recovery",
              "reset link expired",
              "account locked",
              "failed login attempts",
              "account suspended",
              "email verification",
              "contact support for password",
              "password assistance",
              "email address issues",
              "troubleshooting password problems",
              "identity verification",
            ],
          },
          // {
          //   id: "phone-verification",
          //   title: "Why am I not receiving my phone verification code?",
          //   description: "Troubleshooting tips for receiving verification code",
          //   readingTime: "4 min read",
          // },
          {
            id: "auth-method",
            title: "Can I change my authentication method?",
            description: "Learn how to update your sign-in preferences",
            readingTime: "2 min read",
            keywords: [
              "change authentication method",
              "authentication options",
              "login methods",
              "email and password login",
              "Oauth authentication",
              "Google login",
              "authentication settings",
              "sign-in preferences",
              "login options",
              "authentication management",
            ],
          },
          {
            id: "change-password",
            title: "How do I change my account password?",
            description: "Follow the steps below to reset your password",
            readingTime: "3 min read",
            keywords: [
              "change password",
              "update password",
              "password security",
              "password update steps",
              "strong password",
              "password tips",
              "password management",
              "account security",
              "password change guide",
              "secure password",
              "password manager",
              "account settings",
              "reset password",
              "log out and log back in",
            ],
          },
        ],
      },
      {
        title: "Account Settings",
        articles: [
          {
            id: "change-org",
            title: "How can I change my default organization?",
            description: "Steps to update your organization settings",
            readingTime: "2 min read",
            keywords: [
              "change organization",
              "switch organization",
              "default organization",
              "org settings",
              "organization management",
              "company settings",
              "workspace settings",
              "team organization",
              "primary organization",
              "organization switch",
              "multiple organizations",
              "org preferences",
            ],
          },
          {
            id: "change-email",
            title: "How to change your email address",
            description:
              "We do  support changing an email address. This article includes other available options.",
            readingTime: "3 min read",
            keywords: [
              "change email address",
              "update email address",
              "email address change",
              "account settings",
              "email update options",
              "email authentication",
              "email login method",
              "email and password login",
              "Google login email",
              "Facebook login email",
              "Apple login email",
              "email change support",
              "authentication method email",
            ],
          },
        ],
      },
      {
        title: "Subscription & Billing",
        articles: [
          {
            id: "subscription-billing",
            title: "Payment, subscriptions info and cancellations",
            description:
              "Everything You Need to Know About Payments & Subscriptions",
            readingTime: "2 min read",
            keywords: [
              "payment methods",
              "subscriptions info",
              "subscription billing",
              "payment security",
              "credit card payments",
              "PayPal payments",
              "Apple Pay",
              "business payments",
              "wire transfers",
              "ACH payments",
              "subscription billing cycle",
              "upgrade subscription",
              "downgrade subscription",
              "cancel subscription",
              "refund policy",
              "money-back guarantee",
              "monthly subscription",
              "annual subscription",
              "prorated billing",
              "subscription cancellation",
              "data after cancellation",
              "subscription renewals",
              "payment providers",
            ],
          },
        ],
      },
      {
        title: "Support",
        articles: [
          {
            id: "contact-support",
            title: "How can I contact support?",
            description: "Learn how to get in touch with our support team",
            readingTime: "2 min read",
            keywords: [
              "contact support",
              "email support",
              "help center",
              "support team",
              "AI platform support",
              "support options",
              "support@alle-ai.com",
              "help documentation",
              "error messages",
              "issue description",
              "conversation ID",
              "24-hour response",
              "customer support",
              "technical support",
              "common questions",
            ],
          },
        ],
      },
    ],
  },
  "6864268-privacy-and-policies": {
    id: "6864268",
    iconName: "BriefcaseBusiness",
    title: "Privacy and policies",
    description: "Details on terms of service, data privacy and usage policies",
    sections: [
      {
        title: "Privacy",
        articles: [
          {
            id: "privacy-policy",
            title: "Privacy Policy",
            description: "Our commitment to protecting your privacy",
            readingTime: "10 min read",
            keywords: [
              "privacy policy",
              "data protection",
              "user privacy",
              "personal information",
              "data security",
              "privacy rights",
              "data collection",
              "information handling",
              "user data",
              "privacy terms",
              "data privacy",
              "GDPR",
              "privacy compliance",
              "data protection policy",
            ],
          },
          // {
          //   id: "data-usage",
          //   title: "How is my data used?",
          //   description: "Understanding how we handle your information",
          //   readingTime: "5 min read",
          //   keywords: [
          //     "data usage",
          //     "information processing",
          //     "data handling",
          //     "data storage",
          //     "data analysis",
          //     "user information",
          //     "data collection",
          //     "data processing",
          //     "data protection",
          //     "data security",
          //     "information usage",
          //     "data practices",
          //     "data management",
          //   ],
          // },
          {
            id: "data-deletion",
            title: "Requesting data deletion",
            description: "Learn how to request deletion of your personal data",
            readingTime: "3 min read",
            keywords: [
              "delete account",
              "remove data",
              "data deletion",
              "erase account",
              "data removal",
              "account deletion",
              "delete personal data",
              "GDPR rights",
              "right to erasure",
              "data privacy",
              "remove account",
              "delete information",
              "privacy request",
            ],
          },
        ],
      },
      {
        title: "Terms & Policies",
        articles: [
          {
            id: "terms-service",
            title: "Terms of Service",
            description: "Read our terms of service agreement",
            readingTime: "10 min read",
            keywords: [
              "terms of service",
              "user agreement",
              "terms and conditions",
              "service terms",
              "legal terms",
              "user terms",
              "platform terms",
              "usage terms",
              "service agreement",
              "legal agreement",
              "terms of use",
              "user policy",
              "platform rules",
            ],
          },
          {
            id: "usage-policies",
            title: "Usage Policies",
            description: "Guidelines for using our services",
            readingTime: "7 min read",
            keywords: [
              "usage policy",
              "usage guidelines",
              "platform rules",
              "service usage",
              "acceptable use",
              "usage terms",
              "platform policies",
              "user guidelines",
              "service rules",
              "usage restrictions",
              "permitted use",
              "policy guidelines",
              "usage requirements",
            ],
          },
          {
            id: "content-policy",
            title: "Content Policy",
            description: "Understanding what content is allowed",
            readingTime: "5 min read",
            keywords: [
              "AI attribution",
              "AI-driven content",
              "abuse",
              "acceptable content",
              "account suspension",
              "account termination",
              "adult content",
              "artificial intelligence",
              "automated systems",
              "ChatGPT",
              "Claude",
              "community guidelines",
              "content creation",
              "content generation",
              "content moderation",
              "content policy",
              "content removal",
              "content restrictions",
              "content rules",
              "content standards",
              "copyright",
              "creativity",
              "cyber attack",
              "data protection",
              "discrimination",
              "entertainment",
              "explicit content",
              "fraud",
              "graphic content",
              "guidelines violation",
              "harassment",
              "hate speech",
              "human moderation",
              "identity theft",
              "illegal content",
              "innovation",
              "intellectual property",
              "learning",
              "malicious content",
              "malware",
              "patents",
              "personal data",
              "phishing",
              "platform guidelines",
              "platform policies",
              "policy enforcement",
              "policy violation",
              "pornographic",
              "privacy laws",
              "privacy policy",
              "prohibited activities",
              "report content",
              "research",
              "safety guidelines",
              "sensitive data",
              "trademark",
              "user guidelines",
              "violent content",
              "violations",
            ],
          },
        ],
      },
    ],
  },

  "3742473-others": {
    id: "3742473",
    iconName: "FileText",
    title: "Others",
    description: "Anything else",
    sections: [
      {
        title: "Others",
        articles: [
          {
            id: "subscription-discounts",
            title: "Do you offer any discounts?",
            description:
              "Information on available promotions or pricing discounts.",
            readingTime: "3 min read",
            keywords: [],
          },
          {
            id: "models-selection",
            title: "Why Can't You Select Just One Model?",
            description:
              "Learn why selecting multiple models gives you more flexibility and options.",
            readingTime: "2 min read",
            keywords: [],
          },
        ],
      },
    ],
  },
  "7835004-alle-ai-custom": {
    id: "7835004",
    iconName: "FolderCog",
    title: "Alle-AI Custom",
    description: "All things about Alle-AI Custom plan",
    sections: [
      {
        title: "Alle-AI Custom",
        articles: [
          {
            id: "1",
            title: "API",
            description: "Read our apis",
            readingTime: "10 min read",
            keywords: [
              "custom API",
              "API documentation",
              "custom integration",
              "API access",
              "custom features",
              "API endpoints",
              "custom plan",
              "API usage",
              "custom implementation",
              "API reference",
              "custom setup",
              "API guide",
              "custom configuration",
              "enterprise API",
            ],
          },
        ],
      },
    ],
  },
  "5688074-alle-ai-teams": {
    id: "5688074",
    iconName: "Users",
    title: "Alle-AI Teams",
    description:
      "A self-serve subscription plan designed for organizations and businesses wishing to adopt ChatGPT for use among their teams",
    sections: [
      {
        title: "Teams",
        articles: [
          {
            id: "1",
            title: "API",
            description: "Read our apis",
            readingTime: "10 min read",
            keywords: [
              "team API",
              "team integration",
              "collaborative features",
              "team management",
              "team access",
              "group features",
              "team subscription",
              "team setup",
              "organization API",
              "team configuration",
              "multi-user access",
              "team permissions",
              "business teams",
              "team collaboration",
            ],
          },
        ],
      },
    ],
  },
  "11106745-alle-ai-enterprise": {
    id: "11106745",
    iconName: "Building2",
    title: "Alle-AI Enterprise",
    description: "All things about Alle-AI Enterprise",
    sections: [
      {
        title: "Alle-AI Enterprise",
        articles: [
          {
            id: "1",
            title: "API",
            description: "Read our apis",
            readingTime: "10 min read",
            keywords: [
              "enterprise API",
              "enterprise integration",
              "enterprise features",
              "enterprise access",
              "large scale deployment",
              "enterprise setup",
              "enterprise configuration",
              "corporate implementation",
              "enterprise management",
              "business integration",
              "enterprise security",
              "enterprise customization",
              "enterprise solutions",
              "enterprise support",
            ],
          },
        ],
      },
    ],
  },
  // Add other categories...
};
