"use client";
import React from "react";
import { motion } from "framer-motion";
import Image from "next/image";
import Link from "next/link";

const ImageGenerationShowcase: React.FC = () => {
  const prompt = "A futuristic cityscape at night with neon lights";
  const imageExamples = [
    {
      url: "/images/dall-e-3.jpg",
      alt: "DALL·E's interpretation",
      model: "DALL·E",
    },
    {
      url: "/images/titan-image-generator.jpg",
      alt: "Titan's interpretation",
      model: "Titan",
    },
    {
      url: "/images/stable-diffusion.jpg",
      alt: "Stable Diffusion's interpretation",
      model: "Stable Diffusion",
    },
    {
      url: "/images/midjourney.jpg",
      alt: "MidJourney's interpretation",
      model: "MidJourney",
    },
  ];

  return (
    <section className="mb-12">
      <div className="container mx-auto px-4">
        {/* Prompt Section */}
        <div className="text-center mb-6">
          <h2 className="text-2xl font-bold  mb-2">Prompt:</h2>
          <p className="text-lg text-muted-foreground  italic">{`${prompt}`}</p>
        </div>

        {/* Grid of Images */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5 }}
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto"
        >
          {imageExamples.map((image, index) => (
            <motion.div
              key={index}
              className="relative aspect-square rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-200"
              whileHover={{ scale: 1.05 }}
              transition={{ duration: 0.2 }}
            >
              <Image
                src={image.url}
                alt={image.alt}
                fill
                className="object-cover"
              />
              <div className="absolute inset-x-0 bottom-4 flex justify-center">
                <p className="bg-black bg-opacity-70 text-white px-4 py-2 rounded-lg text-sm">
                  Generated by <strong>{image.model}</strong>
                </p>
              </div>
            </motion.div>
          ))}
        </motion.div>

        {/* Call-to-Action Button */}
        {/* <div className="text-center mt-6">
          <Link
            href={"/image"}
            target="_blank"
            className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors duration-200"
          >
            Try Image Generation
          </Link>
        </div> */}
      </div>
    </section>
  );
};

export default ImageGenerationShowcase;
